### ISSUE TITLE
Thumbnails not generated for files with uppercase extensions

### ISSUE THREAD

**Issue by jkblgithub** [SmileyChris/easy-thumbnails#377] opened 2015-08-14 03:48 UTC
I am using the latest version of easy-thumbnails and it is working great except that when a user tries to upload an image with an uppercase extension e.g. image.JPG, no thumbnail gets generated. I have confirmed that my simply changing the JPG to jpg, all works well. Please help - not sure how to fix/work around this.

**Comment by SmileyChris** [comment] 2015-08-14 07:21
Duplicate of #376 (and same questions apply)

**Closed by SmileyChris** 2015-08-14 07:21 UTC
